apiVersion: v1
kind: ConfigMap
metadata:
  name: iris-mlops-config
  namespace: kubeflow
  labels:
    app: iris-mlops
  annotations:
    build-time: "20260530135001"
data:
  MODEL_TYPE: "RandomForestClassifier"
  N_ESTIMATORS: "150"
  TEST_SIZE: "0.3"
  DATASET: "iris"
  TEST_AUTOSYNC: "it_works"