apiVersion: batch/v1
kind: Job
metadata:
  name: iris-prediction-job
  namespace: kubeflow
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: mlops-runner
        image: python:3.9

        envFrom:
        - configMapRef:
            name: iris-mlops-config

        command: ["sh", "-c"]
        args:
        - |
          
          pip install kfp==2.7.0 urllib3==1.26.15 --quiet
          
          echo "Создаем скрипт запуска..."
          cat << 'EOF' > run_pipeline.py
          import os
          from kfp.client import Client

          n_estimators = int(os.environ.get("N_ESTIMATORS", 100))
          test_size = float(os.environ.get("TEST_SIZE", 0.2))
          model_type = os.environ.get("MODEL_TYPE", "RandomForestClassifier")

          print(f"Деревья={n_estimators}, Test_Size={test_size}")

          client = Client()
          run_result = client.create_run_from_pipeline_package(
              pipeline_file='iris_pipeline.yaml', 
              arguments={
                  'n_estimators': n_estimators,
                  'test_size': test_size,
                  'model_type': model_type
              },
              experiment_name='Auto-GitOps-Experiment',
              enable_caching=False
          )
          print(f"Run ID: {run_result.run_id}")
          EOF
          
          wget https://raw.githubusercontent.com/iFaalK/iris-mlops/main/pipelines/iris_pipeline.yaml
        
          python run_pipeline.py

      restartPolicy: Never
  backoffLimit: 1